model:
  base_learning_rate: 6e-5
  target: ldm.models.implict_autoencoder.firststagemodel.FirstStageModel

  params:

    monitor: val/rec_loss
    lossconfig:
      target: ldm.models.implict_autoencoder.encoderloss.EncoderLoss
      params: {}

    ddconfig:
      double_z: False
      z_channels: 12
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 32
      ch_mult: [ 1, 2, 4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [8]
      dropout: 0.0
      num_groups: 8 



    liifconfig:
      hidden_list: [192, 192, 192, 192]
      cell_decode: True
      local_ensemble: True
    trainconfig:
      bsize: 0
      return_img: False
      sample_q: 4096
    
    valconfig:
      return_img: True
      output_size: 128


data:
  batch_size: 1
  root_data: F:/Data_Space/Pelvic1K/processed_128x128_s2.0_block_48
  train_files_name: ./files_name/train_pelvic_2d_256_2.0_3d_128_2.5.txt
  test_files_name: ./files_name/test_pelvic_2d_256_2.0_3d_128_2.5.txt
  num_workers: 1
  pin_memory: True
  use_multi_scale: true
  geo_config: ./geo_config/config_2d_256_s2.0_3d_128_s2.5.yaml

