model:
  base_learning_rate: 6e-5
  target: ldm.models.implict_autoencoder.firststagemodel.FirstStageModel

  params:

    monitor: val/rec_loss
    lossconfig:
      target: ldm.models.implict_autoencoder.encoderloss.EncoderLoss
      params: {}

    ddconfig:
      in_channels: 1
      out_channels: 1
      ch: 32
      resolution: 128
      attn_resolutions: [8]
      ch_mult: [1,2,4]    # num_down = len(ch_mult)-1
      num_blocks: 2
      z_channels: 8
      block_type: "ResnetBlock"    # ResnetBlock, ConvnetBlock
      attn_type: "vanilla"    # to be continued
      dropout: 0.0
      resamp_with_conv: true
      num_groups: 8
    double_z: True

    liifconfig:
      hidden_list: [256, 256, 256, 256]
      cell_decode: True
      local_ensemble: True

data:
  batch_size: 1
  root_data: F:/Data_Space/Pelvic1K/processed_128x128_s2.0_block_48
  train_files_name: ./files_name/train_pelvic_2d_256_2.0_3d_128_2.5.txt
  test_files_name: ./files_name/test_pelvic_2d_256_2.0_3d_128_2.5.txt
  num_workers: 1
  pin_memory: True
  use_multi_scale: true
  geo_config: ./geo_config/config_2d_256_s2.0_3d_128_s2.5.yaml

